name: Docker Image CI

on:
  push:
    tags:
        - "v[0-9]+.[0-9]+.[0-9]+"

jobs:

  # https://stackoverflow.com/a/72959712
  check-branch:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.get_branch.outputs.branch }}
    steps:
  
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get current branch
        id: get_branch
        run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          branch=${raw##*/}
          echo "branch=$branch" >> $GITHUB_OUTPUT
          echo "Branch is $branch."

  deploy:
    runs-on: ubuntu-latest
    needs: check-branch
    if: ${{ needs.check-branch.outputs.branch == 'master' }}
    steps:

      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Build the Docker image
      - run: |
          # docker build . --file Dockerfile --tag my-image-name:$(date +%s)
          echo "The release version is ${{ github.event.release.tag_name }}"


